# Generated by Django 6.0.7 on 2026-09-10 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default='PMJAY', max_length=50, unique=True)),
                ('subtitle', models.CharField(blank=True, default='Government Healthcare Initiative', max_length=255)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('benefits', models.TextField()),
                ('required_documents', models.TextField()),
                ('official_portal_url', models.URLField(default='https://nha.gov.in')),
                ('helpline', models.CharField(default='14555 / 1800-111-565', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display', models.CharField(blank=True, help_text='Cached user name at time of action', max_length=150)),
                ('role', models.CharField(default='SYSTEM', max_length=20)),
                ('action', models.CharField(choices=[('VIEW_RECORD', 'Viewed Medical Record'), ('CREATE_PRESCRIPTION', 'Created Prescription'), ('UPDATE_PRESCRIPTION', 'Updated Prescription'), ('ADD_DOCTOR', 'Added Doctor Account'), ('UPDATE_DOCTOR', 'Updated Doctor Account'), ('DISABLE_DOCTOR', 'Disabled Doctor Account'), ('ENABLE_DOCTOR', 'Enabled Doctor Account'), ('BOOK_APPOINTMENT', 'Booked Appointment'), ('UPDATE_QUEUE_STATUS', 'Updated OPD Queue Status'), ('ORDER_LAB_TEST', 'Ordered Laboratory Test'), ('UPDATE_LAB_RESULT', 'Updated Laboratory Result'), ('DOWNLOAD_REPORT', 'Downloaded Report / Document'), ('CREATE_DISCHARGE_SUMMARY', 'Created Discharge Summary'), ('UPDATE_VACCINATION', 'Updated Vaccination Record'), ('GRANT_CONSENT', 'Granted Record Access Consent'), ('REVOKE_CONSENT', 'Revoked Record Access Consent'), ('DENY_CONSENT', 'Denied Record Access Consent'), ('UPDATE_EMERGENCY_INFO', 'Updated Emergency Information'), ('CREATE_ADVISORY', 'Created Health Advisory'), ('UPDATE_SCHEME', 'Updated Health Scheme'), ('SYSTEM_SECURITY', 'Security & Authorization Check')], max_length=50)),
                ('action_display', models.CharField(blank=True, max_length=100)),
                ('resource_type', models.CharField(help_text='e.g. PatientRecord, Prescription, DoctorProfile, LabOrder', max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=45)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure / Denied')], default='SUCCESS', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Vaccination', 'Vaccination & Immunization Drive'), ('Seasonal Health', 'Seasonal Health & Monsoon Care'), ('Heatwave', 'Heatwave & Extreme Weather'), ('Respiratory Health', 'Respiratory & Air Quality Advisory'), ('Nutrition', 'Nutrition & Lifestyle Wellness'), ('Maternal Health', 'Maternal & Prenatal Health'), ('Child Health', 'Child & Infant Care'), ('Disease Prevention', 'Communicable Disease Prevention'), ('Emergency Preparedness', 'Disaster & Emergency Preparedness')], default='Seasonal Health', max_length=50)),
                ('description', models.TextField()),
                ('precaution_points', models.TextField(blank=True, help_text='Bulleted prevention measures separated by newline')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal Informational'), ('HIGH', 'High Priority Notice'), ('URGENT', 'Urgent Health Alert')], default='NORMAL', max_length=20)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Advisory'), ('ARCHIVED', 'Archived / Expired')], default='ACTIVE', max_length=20)),
                ('issuing_authority', models.CharField(default='Ministry of Health & Family Welfare (MoHFW), Govt of India', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
