# Generated by Django 6.0.7 on 2026-10-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_healthscheme_auditlog_healthadvisory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('VIEW_RECORD', 'Viewed Medical Record'), ('CREATE_PRESCRIPTION', 'Created Prescription'), ('UPDATE_PRESCRIPTION', 'Updated Prescription'), ('ADD_DOCTOR', 'Added Doctor Account'), ('UPDATE_DOCTOR', 'Updated Doctor Account'), ('VERIFY_DOCTOR', 'Verified Doctor Credentials'), ('REJECT_DOCTOR', 'Rejected Doctor Credentials'), ('DISABLE_DOCTOR', 'Disabled Doctor Account'), ('ENABLE_DOCTOR', 'Enabled Doctor Account'), ('ADD_HOSPITAL', 'Registered Hospital Facility'), ('UPDATE_HOSPITAL', 'Updated Hospital Facility'), ('UPDATE_BED_RESOURCE', 'Updated Bed & Resource Capacity'), ('BOOK_APPOINTMENT', 'Booked Appointment'), ('CONFIRM_APPOINTMENT', 'Confirmed Appointment'), ('RESCHEDULE_APPOINTMENT', 'Rescheduled Appointment'), ('CANCEL_APPOINTMENT', 'Cancelled Appointment'), ('UPDATE_QUEUE_STATUS', 'Updated OPD Queue Status'), ('ORDER_LAB_TEST', 'Ordered Laboratory Test'), ('UPDATE_LAB_RESULT', 'Updated Laboratory Result'), ('DOWNLOAD_REPORT', 'Downloaded Report / Document'), ('CREATE_DISCHARGE_SUMMARY', 'Created Discharge Summary'), ('UPDATE_VACCINATION', 'Updated Vaccination Record'), ('GRANT_CONSENT', 'Granted Record Access Consent'), ('REVOKE_CONSENT', 'Revoked Record Access Consent'), ('DENY_CONSENT', 'Denied Record Access Consent'), ('UPDATE_EMERGENCY_INFO', 'Updated Emergency Information'), ('CREATE_ADVISORY', 'Created Health Advisory'), ('UPDATE_SCHEME', 'Updated Health Scheme'), ('SYSTEM_SECURITY', 'Security & Authorization Check')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('HOSPITAL', 'Hospital Admin'), ('ADMIN', 'Government Health Officer / National Admin')], default='PATIENT', max_length=10),
        ),
    ]
