# Generated by Django 6.0.7 on 2026-09-04 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('time_slot', models.CharField(default='10:00 AM - 10:30 AM', max_length=50)),
                ('token_number', models.IntegerField(default=1)),
                ('symptoms', models.TextField(blank=True, default='Routine follow-up / general consultation')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed (पुष्टित)'), ('COMPLETED', 'Completed (पूर्ण)'), ('CANCELLED', 'Cancelled (रद्द)')], default='CONFIRMED', max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-appointment_date', '-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('qualification', models.CharField(default='MBBS, MD', max_length=150)),
                ('department', models.CharField(choices=[('General Medicine', 'General Medicine & Family Health'), ('Cardiology', 'Cardiology & Heart Care'), ('Pulmonology', 'Pulmonology (Respiratory/O2)'), ('Endocrinology', 'Endocrinology & Diabetes'), ('Nephrology', 'Nephrology & Renal Medicine'), ('Pediatrics', 'Pediatrics & Child Health'), ('Orthopedics', 'Orthopedics & Joint Care'), ('Gynecology', 'Obstetrics & Gynecology'), ('Dermatology', 'Dermatology')], default='General Medicine', max_length=80)),
                ('designation', models.CharField(default='Senior Medical Officer', max_length=100)),
                ('experience_years', models.IntegerField(default=12)),
                ('available_days', models.CharField(default='Mon, Tue, Wed, Thu, Fri, Sat', max_length=100)),
                ('max_daily_slots', models.IntegerField(default=35)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['hospital', 'department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('area_name', models.CharField(db_index=True, max_length=150)),
                ('state', models.CharField(default='Delhi', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['city', 'area_name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('facility_type', models.CharField(choices=[('Apex Institute', 'Apex Research & Super-Specialty Institute'), ('Central Govt', 'Central Government Hospital'), ('District Hospital', 'District General Hospital'), ('ESI Hospital', 'ESI Corporation Hospital'), ('CHC', 'Community Health Centre')], default='Central Govt', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(default='+91 11 26588500', max_length=30)),
                ('emergency_available', models.BooleanField(default=True)),
                ('total_beds', models.IntegerField(default=1500)),
                ('opd_timings', models.CharField(default='08:00 AM - 02:00 PM (Mon-Sat)', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
