# Generated by Django 6.0.7 on 2026-09-04 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.doctorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='hospitalarea',
            unique_together={('city', 'area_name')},
        ),
        migrations.AddField(
            model_name='hospitalfacility',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='appointments.hospitalarea'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='appointments.hospitalfacility'),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.hospitalfacility'),
        ),
    ]
