# Generated by Django 6.0.7 on 2026-09-05 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='consultation_notes',
            field=models.TextField(blank=True, help_text='Doctor diagnosis notes and clinical observations'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_reg_id',
            field=models.CharField(blank=True, help_text='Medical Council Registration / Doctor ID', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_present_today',
            field=models.BooleanField(default=True, help_text='Duty presence in hospital today'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed (पुष्टित)'), ('IN_PROGRESS', 'In Consultation (प्रगति पर)'), ('COMPLETED', 'Completed (पूर्ण)'), ('CANCELLED', 'Cancelled (रद्द)')], default='CONFIRMED', max_length=20),
        ),
    ]
