# Generated by Django 6.0.7 on 2026-09-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointmentbooking_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(choices=[('General Medicine', 'General Medicine & Family Health'), ('Cardiology', 'Cardiology & Heart Care'), ('Pulmonology', 'Pulmonology & Respiratory Care'), ('Endocrinology', 'Endocrinology & Diabetes'), ('Nephrology', 'Nephrology & Renal Care'), ('Pediatrics', 'Pediatrics & Child Care'), ('Orthopedics', 'Orthopedics & Joint Care'), ('Gynecology', 'Obstetrics & Gynecology'), ('Dermatology', 'Dermatology & Skin Care'), ('Neurology', 'Neurology & Brain Sciences'), ('Gastroenterology', 'Gastroenterology & Digestive Health'), ('Oncology', 'Oncology & Cancer Care'), ('ENT', 'ENT & Otolaryngology'), ('Ophthalmology', 'Ophthalmology & Eye Care'), ('Urology', 'Urology & Kidney Care'), ('Psychiatry', 'Psychiatry & Behavioral Health'), ('Dentistry', 'Dental Sciences & Maxillofacial Care'), ('Radiology', 'Radiology & Imaging Diagnostics'), ('Emergency Medicine', 'Trauma & Emergency Care'), ('Anesthesiology', 'Anesthesia & Critical Care')], default='General Medicine', max_length=80),
        ),
    ]
