# Generated by Django 6.0.7 on 2026-09-10 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_doctorprofile_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentbooking',
            options={'ordering': ['-appointment_date', 'token_number', '-booked_at']},
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='consultation_room',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='consultation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='opd_token_number',
            field=models.CharField(blank=True, help_text='e.g. A-024', max_length=20),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='session',
            field=models.CharField(choices=[('MORNING', 'Morning OPD'), ('AFTERNOON', 'Afternoon OPD'), ('EVENING', 'Evening OPD')], default='MORNING', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='appointment_duration',
            field=models.IntegerField(default=15, help_text='Duration per patient in minutes'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_room',
            field=models.CharField(default='Room 203', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='opd_end_time',
            field=models.CharField(default='01:00 PM', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='opd_start_time',
            field=models.CharField(default='09:00 AM', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, default='General Medicine', max_length=150),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active (सक्रिय)'), ('INACTIVE', 'Inactive (निष्क्रिय)'), ('ON_LEAVE', 'On Leave (अवकाश पर)'), ('SUSPENDED', 'Suspended (निलंबित)')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked (दर्ज)'), ('CHECKED_IN', 'Checked In (उपस्थित)'), ('WAITING', 'Waiting in Queue (प्रतीक्षारत)'), ('IN_CONSULTATION', 'In Consultation (परामर्श जारी)'), ('COMPLETED', 'Completed (पूर्ण)'), ('CANCELLED', 'Cancelled (रद्द)'), ('NO_SHOW', 'No Show (अनुपस्थित)'), ('CONFIRMED', 'Confirmed (पुष्टित)'), ('IN_PROGRESS', 'In Progress (प्रगति पर)')], default='BOOKED', max_length=20),
        ),
    ]
