# Generated by Django 6.0.7 on 2026-09-25 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointmentbooking_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=60, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='🩺', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hospitalfacility',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hospitalfacility',
            name='district',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hospitalfacility',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalfacility',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalfacility',
            name='pincode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='hospitalfacility',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='appointments.specialty'),
        ),
    ]
