# Generated by Django 6.0.7 on 2026-10-03 04:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_specialty_hospitalfacility_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentbooking',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointments.appointmentbooking'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='leave_status',
            field=models.BooleanField(default=False, help_text='Emergency leave or planned leave flag'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verification_status',
            field=models.CharField(choices=[('VERIFIED', 'Verified (सत्यापित)'), ('PENDING_VERIFICATION', 'Pending Verification (सत्यापन लंबित)'), ('REJECTED', 'Rejected (अस्वीकृत)')], default='VERIFIED', max_length=30),
        ),
        migrations.AddField(
            model_name='hospitalfacility',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hospitalfacility',
            name='email',
            field=models.EmailField(blank=True, default='info@hospital.gov.in', max_length=254),
        ),
        migrations.AddField(
            model_name='hospitalfacility',
            name='license_number',
            field=models.CharField(blank=True, default='MOHFW-HOSP-2026-001', max_length=50),
        ),
        migrations.AddField(
            model_name='hospitalfacility',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active & Verified (सक्रिय)'), ('PENDING_VERIFICATION', 'Pending Verification (सत्यापन लंबित)'), ('SUSPENDED', 'Suspended (निलंबित)'), ('INACTIVE', 'Inactive (निष्क्रिय)')], default='ACTIVE', max_length=30),
        ),
        migrations.AddField(
            model_name='hospitalfacility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked (दर्ज)'), ('CHECKED_IN', 'Checked In (उपस्थित)'), ('WAITING', 'Waiting in Queue (प्रतीक्षारत)'), ('IN_CONSULTATION', 'In Consultation (परामर्श जारी)'), ('COMPLETED', 'Completed (पूर्ण)'), ('CANCELLED', 'Cancelled (रद्द)'), ('NO_SHOW', 'No Show (अनुपस्थित)'), ('RESCHEDULED', 'Rescheduled (पुनर्निर्धारित)'), ('CONFIRMED', 'Confirmed (पुष्टित)'), ('IN_PROGRESS', 'In Progress (प्रगति पर)')], default='BOOKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalfacility',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='appointments.hospitalarea'),
        ),
        migrations.AlterField(
            model_name='hospitalfacility',
            name='facility_type',
            field=models.CharField(choices=[('Apex Institute', 'Apex Research & Super-Specialty Institute'), ('Central Govt', 'Central Government Hospital'), ('District Hospital', 'District General Hospital'), ('ESI Hospital', 'ESI Corporation Hospital'), ('CHC', 'Community Health Centre'), ('Private Hospital', 'Private Hospital / Multispecialty'), ('Trust Hospital', 'Charitable Trust Hospital'), ('PHC', 'Primary Health Centre')], default='Central Govt', max_length=50),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments_list', to='appointments.hospitalfacility')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('hospital', 'name')},
            },
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='department_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors_in_dept', to='appointments.department'),
        ),
        migrations.CreateModel(
            name='HospitalAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Hospital Superintendent / Medical Director', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='appointments.hospitalfacility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_beds_total', models.IntegerField(default=500)),
                ('general_beds_occupied', models.IntegerField(default=320)),
                ('icu_beds_total', models.IntegerField(default=80)),
                ('icu_beds_occupied', models.IntegerField(default=65)),
                ('ventilator_beds_total', models.IntegerField(default=40)),
                ('ventilator_beds_occupied', models.IntegerField(default=28)),
                ('oxygen_beds_total', models.IntegerField(default=200)),
                ('oxygen_beds_occupied', models.IntegerField(default=145)),
                ('oxygen_supply_status', models.CharField(default='Normal (Pressure: 98%)', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_status', to='appointments.hospitalfacility')),
            ],
        ),
    ]
