# Generated by Django 6.0.7 on 2026-09-11 01:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin / Hospital Authority')], default='PATIENT', max_length=20)),
                ('preferred_language', models.CharField(default='en-IN', max_length=15)),
                ('detected_language', models.CharField(default='en-IN', max_length=15)),
                ('active_intent', models.CharField(blank=True, default='UNKNOWN', max_length=60)),
                ('workflow_state', models.CharField(default='IDLE', max_length=60)),
                ('workflow_data', models.JSONField(blank=True, default=dict)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Client safe route & selected resource context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('action', models.CharField(help_text='e.g. CREATE_APPOINTMENT, CANCEL_APPOINTMENT, RESCHEDULE_APPOINTMENT', max_length=60)),
                ('parameters_hash', models.CharField(help_text='SHA-256 hash of normalized parameters', max_length=64)),
                ('parameters', models.JSONField(default=dict)),
                ('summary_text', models.TextField(blank=True, help_text='Human-readable summary presented to user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
