# Generated by Django 6.0.7 on 2026-09-04 07:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('Checkup Reminder', 'Routine Health Checkup'), ('Medication Alert', 'Medication Refill / Dose Alert'), ('Immunization', 'Vaccination / Immunization Drive'), ('Advisory', 'Public Health Advisory (GOI)'), ('Record Update', 'New Lab / Diagnostic Record Added')], default='Checkup Reminder', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('action_tab', models.CharField(default='home', help_text='Tab identifier to navigate to', max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=150)),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('reason_for_visit', models.CharField(max_length=255)),
                ('diagnosis', models.TextField()),
                ('treatment_summary', models.TextField()),
                ('lab_reports_summary', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(default='1 Tablet', max_length=50)),
                ('form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Drops', 'Drops'), ('Ointment', 'Ointment')], default='Tablet', max_length=30)),
                ('morning', models.BooleanField(default=True)),
                ('afternoon', models.BooleanField(default=False)),
                ('night', models.BooleanField(default=True)),
                ('timing', models.CharField(choices=[('Before Food', 'Before Food (खाली पेट)'), ('After Food', 'After Food (भोजन के बाद)'), ('With Food', 'With Food (भोजन के साथ)')], default='After Food', max_length=30)),
                ('duration_days', models.IntegerField(default=7)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, default='Take with warm water as directed.')),
                ('prescribed_by', models.CharField(default='Govt Senior Medical Officer', max_length=150)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='patients.hospitalvisit')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VitalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bp_systolic', models.IntegerField(default=120, help_text='Systolic Blood Pressure in mmHg')),
                ('bp_diastolic', models.IntegerField(default=80, help_text='Diastolic Blood Pressure in mmHg')),
                ('o2_saturation', models.FloatField(default=98.0, help_text='SpO2 percentage (e.g. 98.5)')),
                ('sugar_level', models.FloatField(default=95.0, help_text='Blood Glucose in mg/dL')),
                ('sugar_type', models.CharField(choices=[('Fasting', 'Fasting (FBS)'), ('Postprandial', 'Post-Prandial (PPBS)'), ('Random', 'Random (RBS)')], default='Fasting', max_length=20)),
                ('weight', models.FloatField(default=68.0, help_text='Body Weight in kg')),
                ('blood_percentage', models.FloatField(default=13.8, help_text='Hemoglobin (Hb) in g/dL')),
                ('heart_rate', models.IntegerField(default=72, help_text='Heart Rate in Beats Per Minute (BPM)')),
                ('source', models.CharField(choices=[('Hospital Lab', 'Hospital Lab Report'), ('Doctor Checkup', 'Doctor Clinical Checkup'), ('Patient Logged', 'Patient Self Logged')], default='Hospital Lab', max_length=50)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='vitals_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_snapshots', to='patients.vitalrecord'),
        ),
    ]
