# Generated by Django 6.0.7 on 2026-09-06 14:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='purpose',
            field=models.CharField(default='Relief of symptoms and therapeutic maintenance', help_text='Why tablet is used (Indications & Purpose)', max_length=255),
        ),
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(help_text='e.g. Chest X-Ray PA View, HRCT Chest, CT Brain Non-Contrast', max_length=200)),
                ('modality', models.CharField(choices=[('X-Ray', 'Digital X-Ray Radiograph'), ('CT Scan', 'Computed Tomography (CT Scan)'), ('MRI', 'Magnetic Resonance Imaging (MRI)'), ('Ultrasound', 'Ultrasound & Doppler Sonography')], default='X-Ray', max_length=30)),
                ('body_part', models.CharField(default='Chest', max_length=100)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('hospital_name', models.CharField(default='AIIMS Radiodiagnosis Department', max_length=200)),
                ('radiologist_name', models.CharField(default='Dr. Subhash Chandra (MD Radiology)', max_length=150)),
                ('findings', models.TextField(help_text='Detailed radiological observations and findings')),
                ('impression', models.TextField(help_text='Radiological diagnosis and conclusion summary')),
                ('image_svg', models.TextField(blank=True, help_text='SVG vector image or preview graphic data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
