# Generated by Django 6.0.7 on 2026-09-10 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_prescription_purpose_radiologyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(default='LAB-01', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Hematology', 'Hematology & Blood Counts'), ('Biochemistry', 'Biochemistry & Metabolic Panels'), ('Pathology', 'Clinical Pathology'), ('Microbiology', 'Microbiology & Serology'), ('Cardiology', 'Cardiovascular Diagnostics'), ('Imaging', 'Radiological & Ultrasound Imaging')], default='Hematology', max_length=50)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('reference_range', models.CharField(blank=True, default='', max_length=150)),
                ('sample_type', models.CharField(default='Venous Whole Blood', max_length=100)),
                ('turnaround_hours', models.IntegerField(default=24)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prescription',
            name='generic_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='prescription',
            name='quantity',
            field=models.IntegerField(default=10, help_text='Total units dispensed / prescribed'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped / Discontinued')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthnotification',
            name='category',
            field=models.CharField(choices=[('Checkup Reminder', 'Routine Health Checkup'), ('Medication Alert', 'Medication Refill / Dose Alert'), ('Immunization', 'Vaccination / Immunization Drive'), ('Advisory', 'Public Health Advisory (GOI)'), ('Record Update', 'New Lab / Diagnostic Record Added'), ('Consent Alert', 'Patient Consent Request')], default='Checkup Reminder', max_length=40),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=150)),
                ('doctor_reg_id', models.CharField(blank=True, default='', max_length=100)),
                ('hospital_name', models.CharField(default='Government Hospital', max_length=200)),
                ('purpose', models.CharField(default='Clinical Consultation & Diagnosis', max_length=255)),
                ('scope_medical_history', models.BooleanField(default=True)),
                ('scope_lab_reports', models.BooleanField(default=True)),
                ('scope_prescriptions', models.BooleanField(default=True)),
                ('scope_other_records', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (अनुमति प्रतीक्षारत)'), ('GRANTED', 'Granted (अनुमति स्वीकृत)'), ('DENIED', 'Denied (अनुमति अस्वीकृत)'), ('REVOKED', 'Revoked (अनुमति वापस ली गई)'), ('EXPIRED', 'Expired (समय समाप्त)')], default='GRANTED', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='Consent granted via National Digital Health consent protocol.')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('doctor_name', models.CharField(max_length=150)),
                ('doctor_reg_no', models.CharField(default='MCI-98421', max_length=100)),
                ('hospital_name', models.CharField(default='All India Institute of Medical Sciences (AIIMS)', max_length=200)),
                ('department', models.CharField(default='General Medicine', max_length=100)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('discharge_date', models.DateField(default=django.utils.timezone.now)),
                ('reason_for_admission', models.CharField(max_length=255)),
                ('clinical_findings', models.TextField()),
                ('diagnosis', models.TextField()),
                ('procedures_treatment', models.TextField()),
                ('investigation_results', models.TextField(blank=True)),
                ('condition_at_discharge', models.CharField(default='Stable and Ambulatory (स्थिर एवं स्वस्थ)', max_length=150)),
                ('discharge_medicines', models.TextField(help_text='Prescribed medicines list with dosage and frequency')),
                ('diet_instructions', models.TextField(default='Normal balanced diet, avoid oily and overly salty food. Drink 2.5L water daily.')),
                ('activity_instructions', models.TextField(default='Light walking allowed. Avoid strenuous physical activity for 7 days.')),
                ('follow_up_instructions', models.TextField(default='Review in OPD after 10 days with repeat Fasting Blood Sugar and BP readings.')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-discharge_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(default='Sunil Kumar (Brother)', max_length=150)),
                ('relationship', models.CharField(default='Brother / Primary Kin', max_length=100)),
                ('phone_number', models.CharField(default='+91 9876543210', max_length=20)),
                ('blood_group', models.CharField(default='B+', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('known_allergies', models.TextField(default='Penicillin, Sulfa Drugs (None known for NSAIDs)')),
                ('important_current_meds', models.TextField(default='Telmisartan 40mg (Morning), Metformin 500mg (Night)')),
                ('major_medical_conditions', models.TextField(default='Primary Hypertension, Type-2 Diabetes Mellitus')),
                ('preferred_hospital', models.CharField(default='AIIMS Hospital Trauma Center, New Delhi', max_length=200)),
                ('emergency_hotline', models.CharField(default='108 (Ambulance) / 112 (National Emergency)', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('doctor_name', models.CharField(default='Govt Medical Officer', max_length=150)),
                ('hospital_name', models.CharField(default='Central Govt Hospital', max_length=200)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered (जांच दर्ज)'), ('SAMPLE_COLLECTED', 'Sample Collected (सैंपल प्राप्त)'), ('PROCESSING', 'Processing (परीक्षण जारी)'), ('COMPLETED', 'Completed (रिपोर्ट तैयार)'), ('CANCELLED', 'Cancelled (रद्द)')], default='ORDERED', max_length=30)),
                ('result_value', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('reference_range', models.CharField(blank=True, default='', max_length=150)),
                ('lab_technician', models.CharField(blank=True, default='Certified Lab Technologist', max_length=150)),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('report_file_url', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Clinical observations / sample quality remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='patients.labtest')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=150)),
                ('dose_number', models.IntegerField(default=1)),
                ('date_given', models.DateField(blank=True, null=True)),
                ('hospital_center', models.CharField(default='Govt Primary Health Center', max_length=200)),
                ('provider_name', models.CharField(default='Govt Vaccination Officer', max_length=150)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, default='VAC-2026-X89', max_length=100)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed (लगाई गई)'), ('SCHEDULED', 'Scheduled (नियत)'), ('OVERDUE', 'Overdue (अतिदेय)')], default='COMPLETED', max_length=20)),
                ('notes', models.TextField(blank=True, default='Administered intramuscularly. No adverse reaction observed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_given', 'next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_date', models.DateField(default=django.utils.timezone.now)),
                ('time_slot', models.CharField(choices=[('MORNING', '08:00 AM (Morning / सुबह)'), ('AFTERNOON', '01:00 PM (Afternoon / दोपहर)'), ('NIGHT', '08:00 PM (Night / रात)')], default='MORNING', max_length=20)),
                ('is_taken', models.BooleanField(default=False)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='patients.prescription')),
            ],
            options={
                'ordering': ['-dose_date', 'time_slot'],
                'unique_together': {('prescription', 'patient', 'dose_date', 'time_slot')},
            },
        ),
    ]
