# Generated by Django 6.0.7 on 2026-10-01 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_labtest_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysiotherapyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('back', 'Lumbar Spine & Back Strain'), ('knee', 'Knee Joint & Osteoarthritis'), ('neck', 'Neck & Cervical Spondylosis'), ('shoulder', 'Frozen Shoulder & Rotator Cuff'), ('stroke', 'Post-Stroke & Balance Rehab')], default='back', max_length=30)),
                ('duration_text', models.CharField(default='8:30 mins', max_length=30)),
                ('level_text', models.CharField(default='Beginner Safe', max_length=50)),
                ('instructions', models.TextField(help_text='Step-by-step exercise instructions')),
                ('embed_url', models.URLField(help_text='Embeddable video URL (e.g. YouTube nocookie embed)')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('source_name', models.CharField(default='AIIMS Tele-Physiotherapy Protocol', max_length=150)),
                ('language', models.CharField(default='English / Hindi / Telugu', max_length=50)),
                ('external_video_id', models.CharField(blank=True, default='', help_text='External video ID or source reference', max_length=100)),
                ('external_platform', models.CharField(default='YouTube (Embeddable)', help_text='e.g. YouTube, Vimeo, Educational Medical Host', max_length=60)),
                ('external_url', models.URLField(blank=True, default='', help_text='Direct link if embedding disallowed or for external viewing')),
                ('allows_embedding', models.BooleanField(default=True, help_text='Whether external platform permits iframe embedding')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='dicom_file',
            field=models.FileField(blank=True, help_text='Authorized raw DICOM (.dcm) or imaging study file', null=True, upload_to='radiology_studies/'),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='dicom_frames_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of DICOM frame image URLs'),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='dicom_slice_count',
            field=models.IntegerField(default=48, help_text='Total DICOM slices in imaging study'),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='has_imaging_files',
            field=models.BooleanField(default=False, help_text='True if study files or frames are uploaded'),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='is_dicom',
            field=models.BooleanField(default=False, help_text='True if study is native DICOM format'),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='measurements',
            field=models.TextField(blank=True, default='Standard organ anatomical dimensions within normal limits.', help_text='Quantitative measurements & diagnostic parameters'),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='procedure_name',
            field=models.CharField(blank=True, default='Standard Diagnostic High-Resolution Multi-Slice Acquisition', max_length=200),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='radiologist_reg',
            field=models.CharField(blank=True, default='MCI-98421', max_length=100),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='reason_for_exam',
            field=models.TextField(blank=True, default='Clinical evaluation for persistent pain / routine diagnostic review', help_text='Clinical information / Reason for examination'),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='scan_type',
            field=models.CharField(default='X-Ray', help_text='X-Ray, CT Scan, MRI, Ultrasound, Mammography', max_length=30),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='secure_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Non-predictable cryptographic token for authorized imaging access', max_length=64),
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='modality',
            field=models.CharField(choices=[('X-Ray', 'Digital X-Ray Radiograph'), ('CT Scan', 'Computed Tomography (CT Scan)'), ('MRI', 'Magnetic Resonance Imaging (MRI)'), ('Ultrasound', 'Ultrasound & Doppler Sonography'), ('Mammography', 'Diagnostic Mammography')], default='X-Ray', max_length=30),
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='report_title',
            field=models.CharField(help_text='e.g. Chest X-Ray PA View, HRCT Chest, CT Brain Non-Contrast, Lumbar Spine MRI', max_length=200),
        ),
    ]
