# Generated by Django 6.0.7 on 2026-10-03 05:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointmentbooking_cancellation_reason_and_more'),
        ('patients', '0004_physiotherapyvideo_radiologyreport_dicom_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetedBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Information Advisory (Blue)'), ('WARNING', 'Warning Alert (Orange)'), ('CRITICAL', 'Critical Health Emergency (Red)')], default='WARNING', max_length=20)),
                ('target_type', models.CharField(choices=[('ALL', 'All Citizens Nationally'), ('STATE', 'Specific State'), ('DISTRICT', 'Specific District'), ('PINCODE', 'Specific PIN Code Area'), ('HEALTH_CONDITION', 'Patients with Specific Health Condition'), ('AGE_GROUP', 'Target Age Group')], default='ALL', max_length=30)),
                ('target_value', models.CharField(default='All India', help_text='e.g. Delhi, 110001, Diabetes, 60+', max_length=100)),
                ('issuing_authority', models.CharField(default='Ministry of Health & Family Welfare (MoHFW)', max_length=150)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(help_text='e.g. DL-01-AB-1080', max_length=30, unique=True)),
                ('driver_name', models.CharField(default='Rajesh Kumar', max_length=150)),
                ('driver_phone', models.CharField(default='+91 9810810800', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available (उपलब्ध)'), ('ON_DUTY', 'On Duty (कार्यरत)'), ('MAINTENANCE', 'Under Maintenance (रखरखाव)'), ('OFFLINE', 'Offline (ऑफलाइन)')], default='AVAILABLE', max_length=20)),
                ('latitude', models.FloatField(blank=True, default=28.5672, null=True)),
                ('longitude', models.FloatField(blank=True, default=77.21, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='appointments.hospitalfacility')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(db_index=True, help_text='e.g. Dengue Fever, Viral Illness, Acute Respiratory Infection, Typhoid, Diabetes', max_length=150)),
                ('symptoms', models.TextField(blank=True, default='')),
                ('district', models.CharField(db_index=True, default='New Delhi', max_length=100)),
                ('state', models.CharField(default='Delhi', max_length=100)),
                ('reported_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_records', to='appointments.hospitalfacility')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(choices=[('Accident / Injury', 'Accident & Trauma Injury'), ('Chest pain', 'Severe Chest Pain / Cardiac Event'), ('Breathing difficulty', 'Breathing Difficulty / Low O2'), ('Unconsciousness', 'Unconsciousness / Fainting'), ('Severe bleeding', 'Severe Haemorrhage / Bleeding'), ('Pregnancy emergency', 'Maternity / Pregnancy Emergency'), ('Stroke symptoms', 'Stroke / Neurological Attack'), ('Other emergency', 'Other Acute Medical Emergency')], default='Accident / Injury', max_length=60)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical (Immediate Dispatch)'), ('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='CRITICAL', max_length=20)),
                ('latitude', models.FloatField(default=28.5672)),
                ('longitude', models.FloatField(default=77.21)),
                ('location_address', models.CharField(default='Near Patient Location, New Delhi', max_length=255)),
                ('patient_notes', models.TextField(blank=True, default='Urgent medical assistance required.')),
                ('contact_phone', models.CharField(default='+91 9876543210', max_length=20)),
                ('driver_name', models.CharField(blank=True, default='', max_length=150)),
                ('driver_phone', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Request Received'), ('ACCEPTED', 'Hospital Accepted'), ('AMBULANCE_ASSIGNED', 'Ambulance Assigned'), ('DISPATCHED', 'Ambulance Dispatched'), ('ON_THE_WAY', 'Ambulance On the Way'), ('PICKED_UP', 'Patient Picked Up'), ('REACHED_HOSPITAL', 'Patient Reached Hospital'), ('COMPLETED', 'Request Completed'), ('CANCELLED', 'Request Cancelled')], default='RECEIVED', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='patients.ambulance')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests', to='appointments.hospitalfacility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_rating', models.IntegerField(default=5, help_text='1 to 5 Stars')),
                ('cleanliness_rating', models.IntegerField(default=5)),
                ('waiting_time_rating', models.IntegerField(default=5)),
                ('booking_rating', models.IntegerField(default=5)),
                ('staff_rating', models.IntegerField(default=5)),
                ('overall_rating', models.IntegerField(default=5)),
                ('written_feedback', models.TextField(blank=True, default='')),
                ('complaint_category', models.CharField(choices=[('Doctor behavior', 'Doctor Communication & Behavior'), ('Staff behavior', 'Hospital Support Staff Behavior'), ('Long waiting time', 'Excessive OPD Waiting Time'), ('Billing issue', 'Billing / Scheme Claim Issue'), ('Medicine availability', 'Pharmacy & Medicine Shortage'), ('Lab report delay', 'Lab Report / Diagnostic Delay'), ('Appointment issue', 'Appointment Slot Conflict'), ('Cleanliness', 'Sanitation & Cleanliness'), ('Ambulance/emergency issue', 'Ambulance & SOS Delay'), ('Other', 'Other Feedback / Complaint'), ('None', 'No Complaint / General Praise')], default='None', max_length=50)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_PROGRESS', 'In Progress / Under Review'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated to Govt Admin'), ('REJECTED', 'Closed / Rejected')], default='SUBMITTED', max_length=20)),
                ('response_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='appointments.appointmentbooking')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='appointments.doctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='appointments.hospitalfacility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
